// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ppncauvwwaasozoncpxd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBwbmNhdXZ3d2Fhc296b25jcHhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk0NjQ5MzUsImV4cCI6MjA1NTA0MDkzNX0.iBTujBELZPvCkRL5vk1UZMxaIILbexNz_K8bcSJYlLY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);